### ISSUE TITLE
[Branches] Show a 'deleted' status for branches which have been deleted from remote

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-modelrepository-plugin#140]
Opening this issue to track progress and for discussion for these additional features:

- Show a 'deleted' status for branches which have been deleted from the remote
- Add an option for auto-remove of such branches

**Comment by Phillipus** [comment]
Branch status possible:

| Local | Remote | Tracked | coArchi |
|:-:|:-:|:-:|-|
| X | | | Unpublished|
| X | | X | Deleted |
| X | X |  | Available |
| X | X | X | Available |

**Comment by Phillipus** [comment]
> Show a 'deleted' status for branches which have been deleted from the remote

If a branch is deleted on the remote, the client does not get the "Deleted" status after a "Refresh Model" action. And yet "Refreshe Model" does a Pull action. So what's not happening?

**Comment by Phillipus** [comment]
In `RefreshModelAction` we have this after the Pull action:

```java
catch(Exception ex) {
    // If this exception is thrown then the remote doesn't have the ref which can happen when pulling on a branch,
    // So quietly absorb this and return OK
    if(ex instanceof RefNotAdvertisedException) {
        return PULL_STATUS_OK;
    }
    
    throw ex;
}
```

If we are checked out into a branch and the branch does not exist on the remote we will get this `RefNotAdvertisedException`. So I guess we need to do something about that.

Or is there some git call we can make to get the status of all branches? Isn't this part of 'Fetch'?

**Comment by Phillipus** [comment]
There's a difference between the remote branches that git knows about locally and those that are actually on the remote. Many of our branch status calls interrogate the local repository (and therefore does not connect to the remote).

To get a list of all actual remote branches see https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/ListRemotes.java

Unless there's another way to do this, I'm thinking we need to compare the local list of tracked branches with those in the remote.

**Comment by Phillipus** [comment]
It turns out that all we really need to do is call `Fetch` like this:

```java
FetchCommand fetchCommand = ...;
fetchCommand.setRemoveDeletedRefs(true);
```

Javadoc says - "If set to true, refs are removed which no longer exist in the source"

Indeed, if we call Fetch with this set to true then we get a proper branch status of "Deleted".

We only call Fetch in the background fetch job, nowhere else. So should we call Fetch before Pull? I thought Pull did a Fetch anyway?

**Comment by Phillipus** [comment]
>  I thought Pull did a Fetch anyway?

JGit's `PullCommand` does call `FetchCommand`. But the `FetchCommand` is not accessible in order to set `fetchCommand.setRemoveDeletedRefs(true);`

However, internally the `FetchCommand` code calls this:

```java
Transport transport = ...;
transport.setRemoveDeletedRefs(isRemoveDeletedRefs());`
```

So, this is being set on the `Transport` object. And we have access to this in our callback in our `CredentialsAuthenticator` class where we can do this:

```
public void configure(Transport transport) {
    transport.setCredentialsProvider(new UsernamePasswordCredentialsProvider(npw.getUsername(), npw.getPassword()));
    transport.setRemoveDeletedRefs(true); // <---- HERE!
};
```

So now, when we do a Pull or a Fetch we can get the true branch status in the Branches View.

**Comment by Phillipus** [comment]
Development branch `branching` created for these experiments.

**Comment by Phillipus** [comment]
With this change, if a branch is deleted on the server it will show as "Deleted" in the Branches View when:

1. Any action that does a Pull - "Refresh Model", "Publish" - occurs
1. A fetch in background occurs

So, do we need to draw attention to the fact that a branch has been deleted on the server? This won't be easy in case (2) as this is a background task. 

> Add an option for auto-remove of such branches

Is this required? This would presumably mean to delete the local tracking branch. But there would need to be checks made:

- The user might have this branch checked out
- The user might have uncommitted changes in this branch (if branch is checked out)
- The user might have unpublished commits in this branch

**Comment by jbsarrodie** [comment]
Ok, I did some tests but don't really understand the results:

With a model managed by coArchi (with GitLab) with only a master branch:

## Initial setup
- On GitLab I create a new branch `Test`
- On Archi I refresh m master branch: the new branch `Test` is now listed as `Available`: OK
- On Archi I create and switch to a new branch `MyBranch`, commit a small change and publish. State is now `Available` and the branch is visible in GitLab: OK
- On Archi I create a new branch `MyOtherBranch` but do nothing in it. Branch shows as `Unpublished`: OK

So here is my local state:
![image](https://user-images.githubusercontent.com/5757396/88633623-8ce99e00-d0b5-11ea-836f-ae16089d6800.png)

Here is what I see on GitLab:
![image](https://user-images.githubusercontent.com/5757396/88633680-9ecb4100-d0b5-11ea-8066-70be522dcca0.png)

And here is the `config` file from my local clone:
````
[core]
	symlinks = false
	repositoryformatversion = 0
	filemode = false
	logallrefupdates = true
	autocrlf = input
[remote "origin"]
	url = https://collaborate.mobypic.dev.echonet/os-sit-ap00000/pact-archi/jbsandbox.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[user]
````

**Note:** Only `master` has a remote defined !

## Now some tests
- On GitLab I delete `Test` branch which was not imported locally, then I refresh Archi. The `Test` branch is removed from Archi: OK
- On GitLab I delete `MyBranch` (thus simulating the deletion of the branch by someone else). I would expect the branch status to switch to `Deleted` but it switched back to `Unpublished`: **KO**

## One more test
- On GitLab I create a 'NewBranch` branch, then refresh on Archi (I can now see it), then open it on Archi.

Here is content of `config` file:
````
[core]
	symlinks = false
	repositoryformatversion = 0
	filemode = false
	logallrefupdates = true
	autocrlf = input
[remote "origin"]
	url = https://collaborate.mobypic.dev.echonet/os-sit-ap00000/pact-archi/jbsandbox.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[user]
[branch "NewBranch"]
	remote = origin
	merge = refs/heads/NewBranch
````

- Now it I delete the branch on GitLab and refresh on Archi, the status gets updated to `Deleted`: OK

## Conclusion
It seems to me that the core issue is that there is no tracking information set when publishing, thus leading to bad status in this case (`Available` instead of `Deleted`)

**Comment by Phillipus** [comment]
@jbsarrodie Thanks for the analysis.

> It seems to me that the core issue is that there is no tracking information set when publishing, thus leading to bad status in this case (`Available` instead of `Deleted`)

Bingo!

I've now committed some code that ensures that checks that the current branch has its tracking info set to "origin" when publishing.

**Comment by Phillipus** [comment]
Now that this is working we need to draw attention to deleted branches.

- Show deleted branches in red?
- Add menu item - "Remove Deleted Branches" (not available if a Deleted branch is checked out)?

**Comment by Phillipus** [comment]
@jbsarrodie  I've committed more changes to this branch now.

- Show deleted branches in red in the Branches view
- Add more table columns in the Branches view. Now we have "Branch", "Branch Status", "Latest Commit Author", "Latest Commit Date", and "Commit Status"

I also played around with a "Remove all Deleted branches" action but it turned out to be a bit complicated (lots of additional checks). It works but now that we can see the status of a "Deleted" branch more clearly in the table I personally prefer to use the existing "Delete Branch" action to delete these branches individually.

**Comment by Phillipus** [comment]
New commit - can now switch branch even if there are uncommitted changes. If user selects "No" to commit changes before switching it will go ahead anyway. If there would be a conflict when switching then the user is warned and advised to either commit or abort their changes.

**Comment by jbsarrodie** [comment]
Ok, I've just tested most changes. Here are some remarks, based on current [project](https://github.com/archimatetool/archi-modelrepository-plugin/projects/7):

>Fix branches status and make sure "Deleted" is shown when a local branch track a no more existing branch on remote.

Works as expected

>Show last commit date and author in the "Branches" view

Works as expected

>For branches which have been imported locally: show a more detailed status (up to date, new commits on the remote, unpublished commits...) in the "Branches" view.

Works as expected

>Make it possible to switch to another branch without commiting any changes (there is currently an edge case when the only change is the automatic update of the internal model version).

Doesn't work as expected. The goal is not to switch anyway and keep current model content (which seems to be what you've implemented), but to _Abort Uncommited Changes_ and then switch to the other branch and load its content.

In fact, the goal is to allow a one clic switch even when some changes have been made but should be cancelled. This currently involves a manual call to _Abort Uncommited Changes_ action before a switch. This is not a big deal per se and works most of the time, but this doesn't work when the model is from an old version which is automatically updated by Archi: you'll then get stuck in the branch even when calling _Abort Uncommited Changes_  because this action reloads the model which is then internally updated again, thus changed, thus need a commit...

BTW, while playing with this, I noticed that switching back to a branch gets you to the local ref of this branch, not the remote one (which can be different if someone published some commits in the meantime, i.e. status is "new commits on the remote"). Maybe user should be warned in such case with something like _"You're switching to a branch which got updated in the meantime. Do you want to refresh now?"_.

>Add an way to cleanup "Deleted" branches (ie. branches that exist locally but track a non existent remote branch). Make sure to warn a user if he's still working on one of these branches.

I seen you comment (_I also played around with a "Remove all Deleted branches" action but it turned out to be a bit complicated (lots of additional checks). It works but now that we can see the status of a "Deleted" branch more clearly in the table I personally prefer to use the existing "Delete Branch" action to delete these branches individually._). Maybe we could find a simple way to do it: we in fact only speak about branches which have been checked out locally, so we have to see if local commits are already published (ie. remote should be ahead of local). If this is the case, then the branch can be safely removed. If not, then the user should be prompted with _"Branch XXX is deleted on the remote server but you have unpublished work locally. Do you want to **keep it** or **deleted it anyway** ?"_.

**Comment by jbsarrodie** [comment]
Ok, I've just tested most changes. Here are some remarks, based on current [project](https://github.com/archimatetool/archi-modelrepository-plugin/projects/7):

>Fix branches status and make sure "Deleted" is shown when a local branch track a no more existing branch on remote.

Works as expected

>Show last commit date and author in the "Branches" view

Works as expected

>For branches which have been imported locally: show a more detailed status (up to date, new commits on the remote, unpublished commits...) in the "Branches" view.

Works as expected

>Make it possible to switch to another branch without commiting any changes (there is currently an edge case when the only change is the automatic update of the internal model version).

Doesn't work as expected. The goal is not to switch anyway and keep current model content (which seems to be what you've implemented), but to _Abort Uncommited Changes_ and then switch to the other branch and load its content.

In fact, the goal is to allow a one clic switch even when some changes have been made but should be cancelled. This currently involves a manual call to _Abort Uncommited Changes_ action before a switch. This is not a big deal per se and works most of the time, but this doesn't work when the model is from an old version which is automatically updated by Archi: you'll then get stuck in the branch even when calling _Abort Uncommited Changes_  because this action reloads the model which is then internally updated again, thus changed, thus need a commit...

BTW, while playing with this, I noticed that switching back to a branch gets you to the local ref of this branch, not the remote one (which can be different if someone published some commits in the meantime, i.e. status is "new commits on the remote"). Maybe user should be warned in such case with something like _"You're switching to a branch which got updated in the meantime. Do you want to refresh now?"_.

>Add an way to cleanup "Deleted" branches (ie. branches that exist locally but track a non existent remote branch). Make sure to warn a user if he's still working on one of these branches.

I seen you comment (_I also played around with a "Remove all Deleted branches" action but it turned out to be a bit complicated (lots of additional checks). It works but now that we can see the status of a "Deleted" branch more clearly in the table I personally prefer to use the existing "Delete Branch" action to delete these branches individually._). Maybe we could find a simple way to do it: we in fact only speak about branches which have been checked out locally, so we have to see if local commits are already published (ie. remote should be ahead of local). If this is the case, then the branch can be safely removed. If not, then the user should be prompted with _"Branch XXX is deleted on the remote server but you have unpublished work locally. Do you want to **keep it** or **deleted it anyway** ?"_.

**Comment by Phillipus** [comment]
Thanks for feedback.

> Doesn't work as expected. The goal is not to switch anyway and keep current model content (which seems to be what you've implemented), but to Abort Uncommited Changes and then switch to the other branch and load its content.

OK, what should happen at this point?

1. User tries to switch branch
1. Offer to save model if needed
1. Offer to commit changes if needed
1. If user chooses no to commit then abort all local changes?
1. Switch to other branch

**Comment by jbsarrodie** [comment]
> OK, what should happen at this point?
> 
>     1. User tries to switch branch
>     2. Offer to save model if needed
>     3. Offer to commit changes if needed
>     4. If user chooses no to commit then abort all local changes?
>     5. Switch to other branch

Exactly. In fact, step 4 can also be triggered if user decided not to save the model at step 2. So I would describe it as:
1. User tries to switch branch
2. Offer to save model if needed
  - If user chooses no to save, then offer to either continue switching branch (thus loosing unsaved changes) or abort switching. If user chooses to continue, then abort all local changes.
3. Offer to commit changes if needed
  - If user chooses no to commit, then offer to either continue switching branch (thus loosing uncommitted changes) or abort switching. If user chooses to continue, then abort all local changes.
4. Switch to the other branch and load its content

**Comment by jbsarrodie** [comment]
> OK, what should happen at this point?
> 
>     1. User tries to switch branch
>     2. Offer to save model if needed
>     3. Offer to commit changes if needed
>     4. If user chooses no to commit then abort all local changes?
>     5. Switch to other branch

Exactly. In fact, step 4 can also be triggered if user decided not to save the model at step 2. So I would describe it as:
1. User tries to switch branch
2. Offer to save model if needed
  - If user chooses no to save, then offer to either continue switching branch (thus loosing unsaved changes) or abort switching. If user chooses to continue, then abort all local changes.
3. Offer to commit changes if needed
  - If user chooses no to commit, then offer to either continue switching branch (thus loosing uncommitted changes) or abort switching. If user chooses to continue, then abort all local changes.
4. Switch to the other branch and load its content

**Comment by Phillipus** [comment]
> In fact, step 4 can also be triggered if user decided not to save the model at step 2

Unfortunately this is not possible. As with all actions in coArchi the model has to be saved first because `GraficoModelLoader#loadModel()` will need to close the model if it is open before reloading it, and this will in turn trigger another dialog to save the model if it needs saving. And if the user cancels that then things will get out of sync.

**Comment by jbsarrodie** [comment]
> Unfortunately this is not possible. As with all actions in coArchi the model has to be saved first because `GraficoModelLoader#loadModel()` will need to close the model if it is open before reloading it, and this will in turn trigger another dialog to save the model if it needs saving. And if the user cancels that then things will get out of sync.

But that must be some way to close the model at this point if user doesn't want to save but still want to switch, no ?

**Comment by Phillipus** [comment]
When a model is closed it is done by `EditorModelManager#closeModel()` which will present a dialog (Yes/No/Cancel) to save the model if it needs saving. There is no way to avoid that dialog if the model needs saving so we ask in coArchi to save it first so we can trap the cancel option. I will investigate what happens if we use that dialog instead of coArchi's one.

**Comment by Phillipus** [comment]
I've committed some changes now to `SwitchBranchAction`.

Because of the way things are done in `EditorModelManager#closeModel()` if the model needs saving and the user chooses "Yes" or "No" the model will be closed but any open Views will not be re-opened. This is because normally, `GraficoModelLoader#loadModel()` takes care of closing models and re-opening any Views. I know this sounds complicated but this is a limitation of the way things work in `EditorModelManager` - perhaps we can improve this in cA2.

**Comment by jbsarrodie** [comment]
Crazy ideas:
- Can we unset the dirty flag so that the model is no more seen as changed and thus user won't be prompted to save it ?
- Can we change the file associated with the Resource so that we save the model under a new temporary file, then change it back to its previous path so that it it seen as not changed ?

**Comment by Phillipus** [comment]
> Crazy ideas

Not possible, I'm afraid,

**Comment by jbsarrodie** [comment]
> Not possible, I'm afraid,

Ok, so we have to do it in a different way. The goal is to switch even if the user doesn't want to save/commit its work, so what we could do is:

![image](https://user-images.githubusercontent.com/5757396/92598871-b9dec280-f2a9-11ea-94d5-dcb297d99ead.png)

**Comment by Phillipus** [comment]
If the model is dirty and we save it anyway then a commit will be needed. The flowchart then misses out the stage of offering to commit.

**Comment by jbsarrodie** [comment]
> If the model is dirty and we save it anyway then a commit will be needed. The flowchart then misses out the stage of offering to commit.

The whole point is to not commit these changes ;-) Which become in effect similar to not saving the model.

**Comment by Phillipus** [comment]
What if the user forgets to save and would have liked to have committed before switching?

**Comment by jbsarrodie** [comment]
> What if the user forgets to save and would have liked to have committed before switching?

You mean if the user answer "no" to _You have unsaved changes, Would you like to save you work (yes), continue without saving (no) or abort switching to the other branch (cancel) ?_ ?

In such case I think the answer is clear enough to decide whether the user wants to save (and then we save and offer to commit if needed) or no (and then we save but don't commit).

**Comment by Phillipus** [comment]
So, if the model is dirty and user answers "No" to the save dialog we:

1. Save anyway
1. Abort all local changes
1. Switch branch

?

**Comment by jbsarrodie** [comment]
> So, if the model is dirty and user answers "No" to the save dialog we:
> 
>     1. Save anyway
> 
>     2. Abort all local changes
> 
>     3. Switch branch
> 
> 
> ?

From my diagram:
- Save anyway
- Switch branch
- Load branch content

Remark: no need to reuse _Abort Uncommitted Changes_ action because switching branch and loading it has the same effect.

**Comment by Phillipus** [comment]
> Remark: no need to reuse Abort Uncommitted Changes action because switching branch and loading it has the same effect.

Actually we do. I just checked it.

**Comment by jbsarrodie** [comment]
> Actually we do. I just checked it.

That was my understanding, so we could avoid it and thus speedup things in this specific case.

**Comment by jbsarrodie** [comment]
And BTW, using this action still lead to the same real issue (because model is reloaded, it still gets updated if model is from an old version of Archi but opened in a recent version, thus leading again to a model being changed)

**Comment by Phillipus** [comment]
I've committed some more changes

**Comment by Phillipus** [comment]
>  But what we can do is check if the latest commit we have locally in this branch is accessible from another branch (i.e. it has been merged into another branch before deleting the remote branch). With git this can be done through git branch --contains <commit> (here's a potential way to do it in JGit)

@jbsarrodie  I've thought of a simpler way to do this but maybe there is a flaw in this idea?

- If the latest commit of a branch that is not "master" has one parent then it has not been merged
- If it has more than one parent (usually 2) then it has been merged into another branch

**Comment by jbsarrodie** [comment]
> @jbsarrodie I've thought of a simpler way to do this but maybe there is a flaw in this idea?

Yes there is :-)

> * If the latest commit of a branch that is not "master" has one parent then it has not been merged

No, it simply isn't a merge commit, but you don't know if this commit itself has been merged somewhere.

> * If it has more than one parent (usually 2) then it has been merged into another branch

No, it is simply a merge commit, but you still don't know if this commit itself has been merge.

To know if a commit A has been merged elsewhere, you need to find a commit B which has A has one of its parents... But this is not enough in our case because there might not be a merge commit if the merge has been done fast-forward. So this only solution (and easier IMHO) is to check if the latest commit is included in another branch on remote.

**Comment by Phillipus** [comment]
Perhaps this - https://stackoverflow.com/questions/26644919/how-to-determine-with-jgit-which-branches-have-been-merged-to-master

But checking all branches not just master.

**Comment by jbsarrodie** [comment]
> But checking all branches not just master.

You mean [this](https://stackoverflow.com/questions/40092746/jgit-equivalent-to-git-branch-a-contains-commit-id-merged) (the question is about a variation, but the sample code provided at the begining does exactly what we want.

**Comment by jbsarrodie** [comment]
@Phillipus FYI I've created a dedicated issue for the "delete branch" action. Please use #147 for this topic.

**Comment by jbsarrodie** [comment]
Closing this issue to focus on the other one. Of course this can be reopened if needed.
